branches:
  only:
  - master

env:
  global:
  - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages

cran: http://cran.rstudio.com
warnings_are_errors: true
r_build_args: '--no-manual'
r_check_args: '--no-vignettes --no-manual'

addons:
  apt:
    packages:
      - libgit2-dev

r:
  - oldrel
  - release
  - devel

r_packages:
  - usethis
  - devtools
  - sessioninfo
  - covr
  - data.table
  - origami
  - glmnet
  - hal9001
  - speedglm
  - ranger
  - xgboost
  - arm

r_github_packages:
  - r-lib/sessioninfo
  - r-lib/covr
  - tlverse/hal9001@devel
  - tlverse/sl3@devel

after_success:
  ## coverage
  - travis_wait 60 Rscript -e "covr::codecov(line_exclusions = list('R/utils.R'))"

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change
