---
title: "Efficient causal mediation analysis with intermediate confounders"
author: "[Nima Hejazi](https://nimahejazi.org) and [Iván
  Díaz](https://www.idiaz.xyz/)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
vignette: >
  %\VignetteIndexEntry{Efficient causal mediation analysis with intermediate confounders}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Background

An exposure of interest often affects an outcome directly,
or indirectly by the mediation of some intermediate variables.
Identifying and quantifying the mechanisms underlying causal effects
is an increasingly popular endeavor in public health and the social
sciences, as it can improve understanding of both why and how
treatments can be effective. Such mechanistic knowledge may be
arguably even more important in cases where treatments result in
unanticipated ineffective or even harmful effects. 

Traditional techniques for mediation analysis fare poorly in the face of
intermediate confounding. Classical parameters like the natural (in)direct
effects face a lack of identifiability in cases where mediator-outcome (i.e.,
intermediate) confounders affected by exposure complicate the relationship
between the exposure, mediators, and outcome. @diaz2020nonparametric provide
a theoretical and computational study of the properties of the interventional
(in)direct effect estimands based on the efficiency bound in the non-parametric
statistical model. Among their contributions, @diaz2020nonparametric
- derive the efficient influence function (EIF), an important object in
  semiparametric efficiency theory;
- use the EIF to develop two asymptotically optimal, non-parametric estimators;
  that leverage data-adaptive regression for estimation of nuisance parameters;
  and
- present theoretical conditions under which their proposed estimators are
  consistent, rate multiply robust, $n^{1/2}$-consistent and efficient.

Let $A$ denote a categorical treatment variable, let $Y$ denote a
continuous or binary outcome, let $M$ denote a multivariate mediator,
let $W$ denote a vector of observed pre-treatment covariates, and let
$Z$ denote a mediator-outcome confounder affected by treatment. Let
$O = (W, A, Z, M, Y)$ represent the observed data, and let
$O_1, \ldots, O_n$ denote a sample of $n$ i.i.d.~observations of
$O$. We formalize the definition of our counterfactual variables using
the following non-parametric structural equation model (NPSEM), but
note that equivalent methods may be developed by taking the
counterfactual variables as primitives. Assume the data-generating
process satisfies
\begin{multline}\label{eq:npsem}
  W = f_W(U_W);\ A = f_A(W, U_A);\ Z=f_Z(W, A, U_Z);\\
  M = f_M(W, A, Z, U_M);\ Y = f_Y(W, A, Z, M, U_Y).
\end{multline}
In our illustrative example, we have the following exclusion restrictions:
$M = f_M(W, Z, U_M)$, $Y = f_Y(W, Z, M, U_Y)$, but we present general
methods for the model (\ref{eq:npsem}). Here, the vector of exogenous factors
$U=(U_W,U_A,U_Z,U_M,U_Y)$, and the functions $f$, are assumed
deterministic but unknown. We use $\P$ to denote the distribution
of $O$, and $\Ps$ to denote the distribution of $(O,U)$. We let
$\P$ be an element of the nonparametric statistical model defined
as all continuous densities on $O$ with respect to some dominating
measure $\nu$. Let $\p$ denote the corresponding probability density
function, and $\mathcal{W, Z, M}$ denote the range of the respective
random variables. We let $\E$ and $\E_c$ denote corresponding
expectation operators, and define $\P f = \int f(o)\dd \P(o)$ for a
given function $f(o)$. We use $\Pn$ to denote the empirical distribution
of $O_1, \ldots, O_n$.

In our discussion, the following additional parameterizations will be
useful. We use $\g(a \mid w)$ to denote the probability mass function
of $A=a$ conditional on $W = w$, and $\e(a \mid m, w)$ to denote the
probability mass function of $A=a$ conditional on $(M, W)=(m,w)$. We
use $\m(a,z,m,w)$ to denote the outcome regression function
$\E(Y \mid A = a,Z = z,M = m, W = w)$, and $\q(z \mid a,w)$ and
$\rr(z \mid a,m,w)$ to denote the corresponding conditional densities
of $Z$. For a random variable $X$ we let $X_a$ denote the
counterfactual outcome observed in a hypothetical world in which
$\P(A=a)=1$. For example, we have $Z_a = f_M(W,a,U_Z)$,
$M_a=f_M(W,a,Z_a,U_M)$, and $Y_a=f_Y(W,a,Z_a,M_a,U_Y)$. Likewise, we
let $Y_{a,m} =f_Y(W,a,Z_a,m,U_Y)$ denote the value of the outcome in a
hypothetical world where $\P(A=a,M=m)=1$.

# Methodology

In this work, we define the total effect of $A$ on $Y$ in terms
of a contrast between two user-given values $a', a^{\star} \in \mathcal
A$. Figure \ref{fig:dag} reveals four paths involved in this effect,
namely $A\rightarrow Y$, $A\rightarrow M \rightarrow Y$,
$A\rightarrow Z \rightarrow Y$, and
$A\rightarrow Z \rightarrow M \rightarrow Y$ . One approach to
mediation analysis considers the \emph{natural direct effect
(NDE)} and the \emph{natural indirect effect (NIE)}, defined as
$\E_c(Y_{a',M_{a^{\star}}} - Y_{a^{\star}, M_{a^{\star}}})$ and
$\E_c(Y_{a',M_{a'}} - Y_{a',M_{a^{\star}}})$, respectively
\citep{RobinsGreenland92,Pearl01}. In terms of the NPSEM
(\ref{eq:npsem}), these effects are defined as
\begin{align*}
  \text{NDE} &= \E_c\{f_Y(W,a',Z_{a'},M_{a^{\star}},U_Y) -
               f_Y(W,a^{\star},Z_{a^{\star}},M_{a^{\star}},U_Y)\}\\
  \text{NIE} &= \E_c\{f_Y(W,a',Z_{a'},M_{a'},U_Y) -
               f_Y(W,a',Z_{a'},M_{a^{\star}},U_Y)\}.
\end{align*}
Inspection of the above definitions reveals that the natural direct
effect measures the effect through paths \emph{not} involving the
mediator ($A\rightarrow Y$ and $A\rightarrow Z \rightarrow Y$),
whereas the natural indirect effect measures the effect through paths
involving the mediator ( $A\rightarrow M \rightarrow Y$ and
$A\rightarrow Z \rightarrow M \rightarrow Y$). This effect definition
is appealing because the sum of the natural direct and indirect
effects equals the average treatment effect
$\E_c(Y_1-Y_0)$. Unfortunately, natural direct and indirect effects

[TODO]

# Example

[TODO]

## References

